### ISSUE TITLE
Android app crash java.lang.ClassCastException: android.content.res.Resources cannot be cast to me.saket.resourceinterceptor.InterceptibleResources

### ISSUE THREAD

**Issue by arkivanov** [saket/press#27]
Android emulator API 25
```
Caused by: java.lang.ClassCastException: android.content.res.Resources cannot be cast to me.saket.resourceinterceptor.InterceptibleResources
        at press.widgets.ThemeAwareActivity.applyPaletteTheme(ThemeAwareActivity.kt:33)
        at press.widgets.ThemeAwareActivity.onCreate(ThemeAwareActivity.kt:21)
        at press.home.HomeActivity.onCreate(HomeActivity.kt:18)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
```

**Comment by saket** [comment]
Took me some time, but this should be fixed in the latest version.
