### ISSUE TITLE
Crash after v1.1 update, java.lang.NoSuchFieldException: No field mEdgeGlowTop in class Landroid/widget/ScrollView

### ISSUE THREAD

**Issue by msasikanth** [saket/press#8]
Here is the complete logcat.

Device: Pixel 3,
OS: Android 10 (December security patch)

```
12-10 07:26:59.636  5113  5113 W System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NoSuchFieldException: No field mEdgeGlowTop in class Landroid/widget/ScrollView; (declaration of 'android.widget.ScrollView' appears in /system/framework/framework.jar!classes3.dex)
12-10 07:26:59.636  5113  5113 W System.err: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
12-10 07:26:59.636  5113  5113 W System.err: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:107)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.internal.operators.observable.ObservableTakeUntil$TakeUntilMainObserver.onNext(ObservableTakeUntil.java:79)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.internal.operators.observable.ObservableThrottleFirstTimed$DebounceTimedObserver.onNext(ObservableThrottleFirstTimed.java:82)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.internal.operators.observable.ObservableHide$HideDisposable.onNext(ObservableHide.java:67)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.home.NoteAdapter$onCreateViewHolder$$inlined$apply$lambda$1.onClick(NoteAdapter.kt:25)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.view.View.performClick(View.java:7259)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.view.View.performClickInternal(View.java:7236)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.view.View.access$3600(View.java:801)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.view.View$PerformClick.run(View.java:27892)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.os.Looper.loop(Looper.java:214)
12-10 07:26:59.637  5113  5113 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-10 07:26:59.637  5113  5113 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 07:26:59.637  5113  5113 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-10 07:26:59.637  5113  5113 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-10 07:26:59.637  5113  5113 W System.err: Caused by: java.lang.NoSuchFieldException: No field mEdgeGlowTop in class Landroid/widget/ScrollView; (declaration of 'android.widget.ScrollView' appears in /system/framework/framework.jar!classes3.dex)
12-10 07:26:59.637  5113  5113 W System.err: 	at java.lang.Class.getDeclaredField(Native Method)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.util.Reflection.field(Reflection.kt:20)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.util.ReflectionKt.reflect(Reflection.kt:11)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.theme.ThemedWidgetsKt.themed(ThemedWidgets.kt:64)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.editor.EditorView.<init>(EditorView.kt:80)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.editor.EditorView_AssistedFactory.create(EditorView_AssistedFactory.java:27)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.home.HomeView$setupNoteEditorPage$createEditorView$1.invoke(HomeView.kt:144)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.home.HomeView$setupNoteEditorPage$createEditorView$1.invoke(HomeView.kt:60)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.home.HomeView$setupNoteEditorPage$1.accept(HomeView.kt:155)
12-10 07:26:59.637  5113  5113 W System.err: 	at press.home.HomeView$setupNoteEditorPage$1.accept(HomeView.kt:60)
12-10 07:26:59.637  5113  5113 W System.err: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
```

**Comment by saket** [comment]
Very nice. API 29 brings some official APIs for theming Views in Kotlin removing the need for reflection. Should be fixed by https://github.com/saket/Press/commit/a7b3c928f6c6c76b5b7c90f6b7bcd65bca7e9d95.

**Comment by saket** [comment]
Very nice. API 29 brings some official APIs for theming Views in Kotlin removing the need for reflection. Should be fixed by https://github.com/saket/Press/commit/a7b3c928f6c6c76b5b7c90f6b7bcd65bca7e9d95. Thanks for reporting!
